-- MySQL Script generated by MySQL Workbench
-- Wed May 31 12:36:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8mb4 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`clientes` (
  `ID_Cliente` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido1` VARCHAR(50) NOT NULL,
  `Apellido2` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Correo_Electronico` VARCHAR(100) NULL DEFAULT NULL,
  `Fecha_Registro` DATE NOT NULL,
  `ID_Cliente_Recomendador` TINYINT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Cliente`),
  INDEX `ID_Cliente_Recomendador` (`ID_Cliente_Recomendador` ASC)  ,
  UNIQUE INDEX `Correo_Electronico_UNIQUE` (`Correo_Electronico` ASC)  ,
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC)  ,
  INDEX `nombre_idx` (`Nombre` ASC)  ,
  INDEX `apellido1_idx` (`Apellido1` ASC)  ,
  INDEX `apellido2_idx` (`Apellido2` ASC)  ,
  CONSTRAINT `clientes_ibfk_2`
    FOREIGN KEY (`ID_Cliente_Recomendador`)
    REFERENCES `tienda`.`clientes` (`ID_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`proveedores` (
  `ID_Proveedor` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Fax` VARCHAR(20) NULL DEFAULT NULL,
  `NIF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Proveedor`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC)  ,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`direcciones` (
  `clientes_ID_Cliente` TINYINT(3) NOT NULL,
  `proveedores_ID_Proveedor` TINYINT(3) NOT NULL,
  `Calle` VARCHAR(100) NOT NULL,
  `Numero` TINYINT(4) NULL DEFAULT NULL,
  `Piso` VARCHAR(10) NULL DEFAULT NULL,
  `Puerta` VARCHAR(10) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(50) NOT NULL,
  `CodigoPostal` VARCHAR(10) NOT NULL,
  `Pais` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`clientes_ID_Cliente`, `proveedores_ID_Proveedor`),
  INDEX `fk_direcciones_clientes1_idx` (`clientes_ID_Cliente` ASC)  ,
  INDEX `fk_direcciones_proveedores1_idx` (`proveedores_ID_Proveedor` ASC)  ,
  INDEX `CodigoPostal_idx` (`CodigoPostal` ASC)  ,
  CONSTRAINT `fk_direcciones_clientes1`
    FOREIGN KEY (`clientes_ID_Cliente`)
    REFERENCES `tienda`.`clientes` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direcciones_proveedores1`
    FOREIGN KEY (`proveedores_ID_Proveedor`)
    REFERENCES `tienda`.`proveedores` (`ID_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`empleados` (
  `ID_Empleado` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido1` VARCHAR(50) NOT NULL,
  `Apellido2` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_Empleado`),
  INDEX `nombreEmpleado_idx` (`Nombre` ASC)  ,
  INDEX `apellido1_idx` (`Apellido1` ASC)  ,
  INDEX `apellido2_idx` (`Apellido2` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`gafas` (
  `ID_Gafa` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(50) NOT NULL,
  `Graduacion_Lente1` FLOAT NULL DEFAULT NULL,
  `Graduacion_Lente2` FLOAT NULL DEFAULT NULL,
  `Tipo_Montura` ENUM('flotante', 'pasta', 'metalica') NOT NULL,
  `Color_Montura` VARCHAR(20) NOT NULL,
  `Color_Lente1` VARCHAR(15) NULL DEFAULT NULL,
  `Color_Lente2` VARCHAR(15) NULL DEFAULT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `proveedores_ID_Proveedor` TINYINT(3) NOT NULL,
  PRIMARY KEY (`ID_Gafa`),
  INDEX `fk_gafas_proveedores1_idx` (`proveedores_ID_Proveedor` ASC) IN ,
  INDEX `marca_idx` (`Marca` ASC)  ,
  CONSTRAINT `fk_gafas_proveedores1`
    FOREIGN KEY (`proveedores_ID_Proveedor`)
    REFERENCES `tienda`.`proveedores` (`ID_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`ventas` (
  `ID_Venta` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Fecha_Venta` DATE NOT NULL,
  `gafas_ID_Gafa` TINYINT(3) NOT NULL,
  `empleados_ID_Empleado` TINYINT(3) NOT NULL,
  `clientes_ID_Cliente` TINYINT(3) NOT NULL,
  PRIMARY KEY (`ID_Venta`),
  INDEX `fk_ventas_gafas1_idx` (`gafas_ID_Gafa` ASC)  ,
  INDEX `fk_ventas_empleados1_idx` (`empleados_ID_Empleado` ASC)  ,
  INDEX `fk_ventas_clientes1_idx` (`clientes_ID_Cliente` ASC)  ,
  INDEX `fecha_idx` (`Fecha_Venta` ASC)  ,
  CONSTRAINT `fk_ventas_gafas1`
    FOREIGN KEY (`gafas_ID_Gafa`)
    REFERENCES `tienda`.`gafas` (`ID_Gafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_empleados1`
    FOREIGN KEY (`empleados_ID_Empleado`)
    REFERENCES `tienda`.`empleados` (`ID_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_ID_Cliente`)
    REFERENCES `tienda`.`clientes` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
